import { I8085_INSTRUCTIONS } from "./instruction-set";

export const I8085_INSTRUCTION_INFO: Record<
  (typeof I8085_INSTRUCTIONS)[number],
  string
> = {
  MOV: "Copies one register or M(HL memory) byte into another.",
  MVI: "Loads an 8-bit immediate byte into a register or M.",
  LXI: "Loads a 16-bit immediate word into a register pair or SP.",
  LDA: "Loads A from the direct 16-bit memory address.",
  STA: "Stores A into the direct 16-bit memory address.",
  LHLD: "Loads L and H from two consecutive memory bytes.",
  SHLD: "Stores L and H into two consecutive memory bytes.",
  LDAX: "Loads A from memory addressed by BC or DE.",
  STAX: "Stores A into memory addressed by BC or DE.",
  XCHG: "Exchanges DE and HL.",
  ADD: "Adds a register or M byte to A.",
  ADC: "Adds a register or M byte plus carry to A.",
  ADI: "Adds an 8-bit immediate byte to A.",
  ACI: "Adds an 8-bit immediate byte plus carry to A.",
  SUB: "Subtracts a register or M byte from A.",
  SBB: "Subtracts a register or M byte plus borrow from A.",
  SUI: "Subtracts an 8-bit immediate byte from A.",
  SBI: "Subtracts an 8-bit immediate byte plus borrow from A.",
  INR: "Increments a register or M byte without changing carry.",
  DCR: "Decrements a register or M byte without changing carry.",
  INX: "Increments a register pair or SP without changing flags.",
  DCX: "Decrements a register pair or SP without changing flags.",
  DAD: "Adds a register pair or SP to HL and updates carry.",
  DAA: "Decimal-adjusts A after packed BCD addition.",
  ANA: "ANDs a register or M byte with A.",
  ANI: "ANDs an 8-bit immediate byte with A.",
  XRA: "XORs a register or M byte with A.",
  XRI: "XORs an 8-bit immediate byte with A.",
  ORA: "ORs a register or M byte with A.",
  ORI: "ORs an 8-bit immediate byte with A.",
  CMP: "Compares a register or M byte with A without storing the result.",
  CPI: "Compares an 8-bit immediate byte with A.",
  RLC: "Rotates A left and copies bit 7 into carry and bit 0.",
  RRC: "Rotates A right and copies bit 0 into carry and bit 7.",
  RAL: "Rotates A left through carry.",
  RAR: "Rotates A right through carry.",
  CMA: "Complements every bit in A.",
  CMC: "Complements the carry flag.",
  STC: "Sets the carry flag.",
  JMP: "Unconditionally jumps to a 16-bit address.",
  JNZ: "Jumps if zero flag is reset.",
  JZ: "Jumps if zero flag is set.",
  JNC: "Jumps if carry flag is reset.",
  JC: "Jumps if carry flag is set.",
  JPO: "Jumps if parity is odd.",
  JPE: "Jumps if parity is even.",
  JP: "Jumps if sign flag is reset.",
  JM: "Jumps if sign flag is set.",
  CALL: "Calls a subroutine at a 16-bit address.",
  CNZ: "Calls if zero flag is reset.",
  CZ: "Calls if zero flag is set.",
  CNC: "Calls if carry flag is reset.",
  CC: "Calls if carry flag is set.",
  CPO: "Calls if parity is odd.",
  CPE: "Calls if parity is even.",
  CP: "Calls if sign flag is reset.",
  CM: "Calls if sign flag is set.",
  RET: "Returns from a subroutine by popping PC.",
  RNZ: "Returns if zero flag is reset.",
  RZ: "Returns if zero flag is set.",
  RNC: "Returns if carry flag is reset.",
  RC: "Returns if carry flag is set.",
  RPO: "Returns if parity is odd.",
  RPE: "Returns if parity is even.",
  RP: "Returns if sign flag is reset.",
  RM: "Returns if sign flag is set.",
  RST: "Calls one of eight fixed restart vectors.",
  PCHL: "Loads PC from HL.",
  PUSH: "Pushes a register pair or PSW onto the stack.",
  POP: "Pops stack bytes into a register pair or PSW.",
  XTHL: "Exchanges HL with the top word on the stack.",
  SPHL: "Loads SP from HL.",
  IN: "Reads an input port byte into A.",
  OUT: "Writes A to an output port.",
  EI: "Enables maskable interrupts.",
  DI: "Disables maskable interrupts.",
  SIM: "Sets interrupt masks and serial output state from A.",
  RIM: "Reads interrupt mask and serial input state into A.",
  NOP: "Does nothing for one instruction cycle.",
  HLT: "Halts execution.",
};
